export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_SUCCEEDED = "GET_ORDER_SUCCEEDED";
export const GET_ORDER_FAILED = "GET_ORDER_FAILED";

export const ADD_ORDER = "ADD_ORDER";
export const ADD_ORDER_SUCCEEDED = "ADD_ORDER_SUCCEEDED";
export const ADD_ORDER_FAILED = "ADD_ORDER_FAILED";

export const MOD_ORDER = "MOD_ORDER";
export const MOD_ORDER_SUCCEEDED = "MOD_ORDER_SUCCEEDED";
export const MOD_ORDER_FAILED = "MOD_ORDER_FAILED";

export const DEL_ORDER = "DEL_ORDER";
export const DEL_ORDER_SUCCEEDED = "DEL_ORDER_SUCCEEDED";
export const DEL_ORDER_FAILED = "DEL_ORDER_FAILED";

export const UPDATE_SSR_ORDER = "UPDATE_SSR_ORDER";

export const SEARCH_ORDER = "SEARCH_ORDER";
export const SEARCH_ORDER_SUCCEEDED = "SEARCH_ORDER_SUCCEEDED";
export const SEARCH_ORDER_FAILED = "SEARCH_ORDER_FAILED";

export const BATCH_DEL_ORDER = "BATCH_DEL_ORDER";
export const BATCH_DEL_ORDER_SUCCEEDED = "BATCH_DEL_ORDER_SUCCEEDED";
export const BATCH_DEL_ORDER_FAILED = "BATCH_DEL_ORDER_FAILED";
