export const GET_PAYMENT = "GET_PAYMENT";
export const GET_PAYMENT_SUCCEEDED = "GET_PAYMENT_SUCCEEDED";
export const GET_PAYMENT_FAILED = "GET_PAYMENT_FAILED";

export const ADD_PAYMENT = "ADD_PAYMENT";
export const ADD_PAYMENT_SUCCEEDED = "ADD_PAYMENT_SUCCEEDED";
export const ADD_PAYMENT_FAILED = "ADD_PAYMENT_FAILED";

export const MOD_PAYMENT = "MOD_PAYMENT";
export const MOD_PAYMENT_SUCCEEDED = "MOD_PAYMENT_SUCCEEDED";
export const MOD_PAYMENT_FAILED = "MOD_PAYMENT_FAILED";

export const DEL_PAYMENT = "DEL_PAYMENT";
export const DEL_PAYMENT_SUCCEEDED = "DEL_PAYMENT_SUCCEEDED";
export const DEL_PAYMENT_FAILED = "DEL_PAYMENT_FAILED";

export const UPDATE_SSR_PAYMENT = "UPDATE_SSR_PAYMENT";

export const SEARCH_PAYMENT = "SEARCH_PAYMENT";
export const SEARCH_PAYMENT_SUCCEEDED = "SEARCH_PAYMENT_SUCCEEDED";
export const SEARCH_PAYMENT_FAILED = "SEARCH_PAYMENT_FAILED";

export const BATCH_DEL_PAYMENT = "BATCH_DEL_PAYMENT";
export const BATCH_DEL_PAYMENT_SUCCEEDED = "BATCH_DEL_PAYMENT_SUCCEEDED";
export const BATCH_DEL_PAYMENT_FAILED = "BATCH_DEL_PAYMENT_FAILED";
