export const GET_USER = "GET_USER";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCEEDED = "ADD_USER_SUCCEEDED";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const MOD_USER = "MOD_USER";
export const MOD_USER_SUCCEEDED = "MOD_USER_SUCCEEDED";
export const MOD_USER_FAILED = "MOD_USER_FAILED";

export const DEL_USER = "DEL_USER";
export const DEL_USER_SUCCEEDED = "DEL_USER_SUCCEEDED";
export const DEL_USER_FAILED = "DEL_USER_FAILED";

export const UPDATE_SSR_USER = "UPDATE_SSR_USER";

export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCEEDED = "SEARCH_USER_SUCCEEDED";
export const SEARCH_USER_FAILED = "SEARCH_USER_FAILED";

export const BATCH_DEL_USER = "BATCH_DEL_USER";
export const BATCH_DEL_USER_SUCCEEDED = "BATCH_DEL_USER_SUCCEEDED";
export const BATCH_DEL_USER_FAILED = "BATCH_DEL_USER_FAILED";
