export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCEEDED = "GET_CATEGORY_SUCCEEDED";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCEEDED = "ADD_CATEGORY_SUCCEEDED";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const MOD_CATEGORY = "MOD_CATEGORY";
export const MOD_CATEGORY_SUCCEEDED = "MOD_CATEGORY_SUCCEEDED";
export const MOD_CATEGORY_FAILED = "MOD_CATEGORY_FAILED";

export const DEL_CATEGORY = "DEL_CATEGORY";
export const DEL_CATEGORY_SUCCEEDED = "DEL_CATEGORY_SUCCEEDED";
export const DEL_CATEGORY_FAILED = "DEL_CATEGORY_FAILED";

export const UPDATE_SSR_CATEGORY = "UPDATE_SSR_CATEGORY";

export const SEARCH_CATEGORY = "SEARCH_CATEGORY";
export const SEARCH_CATEGORY_SUCCEEDED = "SEARCH_CATEGORY_SUCCEEDED";
export const SEARCH_CATEGORY_FAILED = "SEARCH_CATEGORY_FAILED";

export const BATCH_DEL_CATEGORY = "BATCH_DEL_CATEGORY";
export const BATCH_DEL_CATEGORY_SUCCEEDED = "BATCH_DEL_CATEGORY_SUCCEEDED";
export const BATCH_DEL_CATEGORY_FAILED = "BATCH_DEL_CATEGORY_FAILED";
