export const GET_CART = "GET_CART";
export const GET_CART_SUCCEEDED = "GET_CART_SUCCEEDED";
export const GET_CART_FAILED = "GET_CART_FAILED";

export const ADD_CART = "ADD_CART";
export const ADD_CART_SUCCEEDED = "ADD_CART_SUCCEEDED";
export const ADD_CART_FAILED = "ADD_CART_FAILED";

export const MOD_CART = "MOD_CART";
export const MOD_CART_SUCCEEDED = "MOD_CART_SUCCEEDED";
export const MOD_CART_FAILED = "MOD_CART_FAILED";

export const DEL_CART = "DEL_CART";
export const DEL_CART_SUCCEEDED = "DEL_CART_SUCCEEDED";
export const DEL_CART_FAILED = "DEL_CART_FAILED";

export const UPDATE_SSR_CART = "UPDATE_SSR_CART";

export const SEARCH_CART = "SEARCH_CART";
export const SEARCH_CART_SUCCEEDED = "SEARCH_CART_SUCCEEDED";
export const SEARCH_CART_FAILED = "SEARCH_CART_FAILED";

export const BATCH_DEL_CART = "BATCH_DEL_CART";
export const BATCH_DEL_CART_SUCCEEDED = "BATCH_DEL_CART_SUCCEEDED";
export const BATCH_DEL_CART_FAILED = "BATCH_DEL_CART_FAILED";
