export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCEEDED = "GET_PRODUCT_SUCCEEDED";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCEEDED = "ADD_PRODUCT_SUCCEEDED";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const MOD_PRODUCT = "MOD_PRODUCT";
export const MOD_PRODUCT_SUCCEEDED = "MOD_PRODUCT_SUCCEEDED";
export const MOD_PRODUCT_FAILED = "MOD_PRODUCT_FAILED";

export const DEL_PRODUCT = "DEL_PRODUCT";
export const DEL_PRODUCT_SUCCEEDED = "DEL_PRODUCT_SUCCEEDED";
export const DEL_PRODUCT_FAILED = "DEL_PRODUCT_FAILED";

export const UPDATE_SSR_PRODUCT = "UPDATE_SSR_PRODUCT";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const SEARCH_PRODUCT_SUCCEEDED = "SEARCH_PRODUCT_SUCCEEDED";
export const SEARCH_PRODUCT_FAILED = "SEARCH_PRODUCT_FAILED";

export const BATCH_DEL_PRODUCT = "BATCH_DEL_PRODUCT";
export const BATCH_DEL_PRODUCT_SUCCEEDED = "BATCH_DEL_PRODUCT_SUCCEEDED";
export const BATCH_DEL_PRODUCT_FAILED = "BATCH_DEL_PRODUCT_FAILED";
