export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCEEDED = "GET_BANNER_SUCCEEDED";
export const GET_BANNER_FAILED = "GET_BANNER_FAILED";

export const ADD_BANNER = "ADD_BANNER";
export const ADD_BANNER_SUCCEEDED = "ADD_BANNER_SUCCEEDED";
export const ADD_BANNER_FAILED = "ADD_BANNER_FAILED";

export const MOD_BANNER = "MOD_BANNER";
export const MOD_BANNER_SUCCEEDED = "MOD_BANNER_SUCCEEDED";
export const MOD_BANNER_FAILED = "MOD_BANNER_FAILED";

export const DEL_BANNER = "DEL_BANNER";
export const DEL_BANNER_SUCCEEDED = "DEL_BANNER_SUCCEEDED";
export const DEL_BANNER_FAILED = "DEL_BANNER_FAILED";

export const UPDATE_SSR_BANNER = "UPDATE_SSR_BANNER";

export const SEARCH_BANNER = "SEARCH_BANNER";
export const SEARCH_BANNER_SUCCEEDED = "SEARCH_BANNER_SUCCEEDED";
export const SEARCH_BANNER_FAILED = "SEARCH_BANNER_FAILED";

export const BATCH_DEL_BANNER = "BATCH_DEL_BANNER";
export const BATCH_DEL_BANNER_SUCCEEDED = "BATCH_DEL_BANNER_SUCCEEDED";
export const BATCH_DEL_BANNER_FAILED = "BATCH_DEL_BANNER_FAILED";
