export const GET_ADDRESS = "GET_ADDRESS";
export const GET_ADDRESS_SUCCEEDED = "GET_ADDRESS_SUCCEEDED";
export const GET_ADDRESS_FAILED = "GET_ADDRESS_FAILED";

export const ADD_ADDRESS = "ADD_ADDRESS";
export const ADD_ADDRESS_SUCCEEDED = "ADD_ADDRESS_SUCCEEDED";
export const ADD_ADDRESS_FAILED = "ADD_ADDRESS_FAILED";

export const MOD_ADDRESS = "MOD_ADDRESS";
export const MOD_ADDRESS_SUCCEEDED = "MOD_ADDRESS_SUCCEEDED";
export const MOD_ADDRESS_FAILED = "MOD_ADDRESS_FAILED";

export const DEL_ADDRESS = "DEL_ADDRESS";
export const DEL_ADDRESS_SUCCEEDED = "DEL_ADDRESS_SUCCEEDED";
export const DEL_ADDRESS_FAILED = "DEL_ADDRESS_FAILED";

export const UPDATE_SSR_ADDRESS = "UPDATE_SSR_ADDRESS";

export const SEARCH_ADDRESS = "SEARCH_ADDRESS";
export const SEARCH_ADDRESS_SUCCEEDED = "SEARCH_ADDRESS_SUCCEEDED";
export const SEARCH_ADDRESS_FAILED = "SEARCH_ADDRESS_FAILED";

export const BATCH_DEL_ADDRESS = "BATCH_DEL_ADDRESS";
export const BATCH_DEL_ADDRESS_SUCCEEDED = "BATCH_DEL_ADDRESS_SUCCEEDED";
export const BATCH_DEL_ADDRESS_FAILED = "BATCH_DEL_ADDRESS_FAILED";
