export const GET_ORDER_ITEM = "GET_ORDER_ITEM";
export const GET_ORDER_ITEM_SUCCEEDED = "GET_ORDER_ITEM_SUCCEEDED";
export const GET_ORDER_ITEM_FAILED = "GET_ORDER_ITEM_FAILED";

export const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
export const ADD_ORDER_ITEM_SUCCEEDED = "ADD_ORDER_ITEM_SUCCEEDED";
export const ADD_ORDER_ITEM_FAILED = "ADD_ORDER_ITEM_FAILED";

export const MOD_ORDER_ITEM = "MOD_ORDER_ITEM";
export const MOD_ORDER_ITEM_SUCCEEDED = "MOD_ORDER_ITEM_SUCCEEDED";
export const MOD_ORDER_ITEM_FAILED = "MOD_ORDER_ITEM_FAILED";

export const DEL_ORDER_ITEM = "DEL_ORDER_ITEM";
export const DEL_ORDER_ITEM_SUCCEEDED = "DEL_ORDER_ITEM_SUCCEEDED";
export const DEL_ORDER_ITEM_FAILED = "DEL_ORDER_ITEM_FAILED";

export const UPDATE_SSR_ORDER_ITEM = "UPDATE_SSR_ORDER_ITEM";

export const SEARCH_ORDER_ITEM = "SEARCH_ORDER_ITEM";
export const SEARCH_ORDER_ITEM_SUCCEEDED = "SEARCH_ORDER_ITEM_SUCCEEDED";
export const SEARCH_ORDER_ITEM_FAILED = "SEARCH_ORDER_ITEM_FAILED";

export const BATCH_DEL_ORDER_ITEM = "BATCH_DEL_ORDER_ITEM";
export const BATCH_DEL_ORDER_ITEM_SUCCEEDED = "BATCH_DEL_ORDER_ITEM_SUCCEEDED";
export const BATCH_DEL_ORDER_ITEM_FAILED = "BATCH_DEL_ORDER_ITEM_FAILED";
